{
    'name': 'Hatta Reports',
    'version': '0.1',
    'summary': 'Hatta Reports',
    'description': 'Hatta Reports',
    'author': 'FourmalTech',
    'website': 'www.fourmaltech.com',
    'depends': ['purchase','stock','hatta_trading','account_invoice_fixed_discount'],
    'data': [
        'security/ir.model.access.csv',
        'reports/external_layout.xml',
        # 'reports/purchase_order_status.xml',
        'reports/sale_invoice_summary_report.xml',
        # 'reports/sale_order_summary_report.xml',
        # 'reports/purchase_invoice_summary.xml',
        # 'reports/sales_return_inventory.xml',
        # 'reports/delivery_summary.xml',
        # 'reports/sale_purchase_analysis.xml',
        # 'reports/consolidated_sale_report.xml',
        # 'reports/quotation_submission_report.xml',
        # 'reports/upcoming_quotation_submission.xml',
        # 'reports/upcoming_deliveries.xml',
        # 'reports/delivery_notedelivery_note.xml',
        # 'reports/refund.xml',
        'reports/sale_tax_invoice.xml',
        # 'reports/sale_return.xml',
        # 'reports/sales_return_inventory.xml',
        # 'reports/partner_ledger.xml',
        'reports/cost_sheet_component_report.xml',
        'reports/tr_report.xml',
        'reports/tr_status_report.xml',
        'reports/credit_note.xml',
        'reports/send_quotation_status.xml',
        # 'reports/po_summary_report.xml',
        # 'reports/shipment_payment_report.xml',
        # 'reports/shipment_insurance_report.xml',
        'wizard/cs_component_wizard.xml',
        'wizard/tr_wizard.xml',
        'wizard/tr_status_wizard.xml',
        # 'wizard/delivery_summary_wizard.xml',
        # 'wizard/po_status_report_wizard.xml',
        # 'wizard/po_summary_wizard.xml',
        # 'wizard/sales_return_wizard.xml',
        'wizard/sale_invoice_summary_wizard.xml',
        # 'wizard/purchase_invoice_summary_wizard.xml',
        # 'wizard/sale_purchase_analysis_wizard.xml',
        # 'wizard/consolidated_so_report_wizard.xml',
        # 'wizard/quotation_submission_wizard.xml',
        # 'wizard/upcoming_quotation_wizard.xml',
        # 'wizard/upcoming_deliveries_wizard.xml',
        # 'wizard/shipment_payment_wizard.xml',
        # 'wizard/shipment_insurance_wizard.xml',
        # 'wizard/client_purchase_order_status_wizard.xml',
        # 'reports/client_purchase_order_status_reportclient_purchase_order_status.xml',
    ],
    'qweb': [
            "static/src/xml/*.xml",
            ],
    'installable': True,
    'auto_install': False,
}